from __future__ import annotations

"""
TARZAN SNAJPER CALIBER

Caliber ujednolica nazwę sygnału:
    raw_signal -> logical_signal

Nie formatuje wartości.
Nie wskazuje targetów.
Nie wysyła na Nextion.

Po czyszczeniu usunięto stary techniczny skan HMI bez realnego znaczenia
w warstwie Caliber. Zostają tylko aktywne aliasy sygnałów i kilka wyjątków,
które nadal są używane przez Bridge / Nextion.
"""

from typing import Dict


DEFAULT_TARZAN_SNAJPER_SIGNAL_MAP: Dict[str, str] = {'par_rrp_p1_dir': 'rrp_p1_dir',
 'par_rrp_p1_sens': 'rrp_p1_sens',
 'par_rrp_p1_val': 'rrp_p1_value',
 'par_rrp_p2_dir': 'rrp_p2_dir',
 'par_rrp_p2_sens': 'rrp_p2_sens',
 'par_rrp_p2_val': 'rrp_p2_value',
 'par_shock': 'sensor_shock',
 'par_laser': 'sensor_laser',
 'par_limits': 'sensor_limits',
 'par_light': 'sensor_light',
 'par_temp': 'sensor_temp',
 'par_xyz': 'sensor_xyz',
 'par_level_x': 'level_x',
 'par_level_y': 'level_y',
 'par_level_z': 'level_z',
 'par_take_number': 'take_number',
 'par_take_status': 'take_status',
 'par_take_timecode': 'take_timecode',
 'par_take_clap': 'take_clap',
 'take_main.b_clap.val': 'nextion_take_main_b_clap_val',
 'take_main.t1.txt': 'nextion_take_main_t1_txt',
 'take_timecode': 'take_timecode',
 'axis_0_value': 'axis_0_value',
 'axis_1_value': 'axis_1_value',
 'axis_2_value': 'axis_2_value',
 'axis_3_value': 'axis_3_value',
 'axis_4_value': 'axis_4_value',
 'axis_5_value': 'axis_5_value',
 'sensor_level_x': 'level_x',
 'sensor_level_y': 'level_y',
 'nextion_ui_cut': 'nextion_ui_cut',
 'ehr_axis_0_curve': 'ehr_axis_0_curve',
 'ehr_axis_0_metrics': 'ehr_axis_0_metrics',
 'ehr_axis_0_step_preview': 'ehr_axis_0_step_preview',
 'ehr_axis_1_curve': 'ehr_axis_1_curve',
 'ehr_axis_1_metrics': 'ehr_axis_1_metrics',
 'ehr_axis_1_step_preview': 'ehr_axis_1_step_preview',
 'ehr_axis_2_curve': 'ehr_axis_2_curve',
 'ehr_axis_2_metrics': 'ehr_axis_2_metrics',
 'ehr_axis_2_step_preview': 'ehr_axis_2_step_preview',
 'ehr_axis_3_curve': 'ehr_axis_3_curve',
 'ehr_axis_3_metrics': 'ehr_axis_3_metrics',
 'ehr_axis_3_step_preview': 'ehr_axis_3_step_preview',
 'ehr_axis_4_curve': 'ehr_axis_4_curve',
 'ehr_axis_4_metrics': 'ehr_axis_4_metrics',
 'ehr_axis_4_step_preview': 'ehr_axis_4_step_preview',
 'ehr_axis_5_curve': 'ehr_axis_5_curve',
 'ehr_axis_5_metrics': 'ehr_axis_5_metrics',
 'ehr_axis_5_step_preview': 'ehr_axis_5_step_preview',
 'ehr_take_slot_0_status': 'ehr_take_slot_0_status',
 'ehr_take_slot_1_status': 'ehr_take_slot_1_status',
 'ehr_take_slot_2_status': 'ehr_take_slot_2_status',
 'ehr_take_slot_3_status': 'ehr_take_slot_3_status',
 'ehr_take_slot_4_status': 'ehr_take_slot_4_status',
 'ehr_take_slot_5_status': 'ehr_take_slot_5_status',
 'ehr_take_slot_6_status': 'ehr_take_slot_6_status',
 'ehr_take_slot_7_status': 'ehr_take_slot_7_status',
 'sandbox_curve': 'sandbox_curve',
 'sandbox_metrics': 'sandbox_metrics',
 'sandbox_step_preview': 'sandbox_step_preview',
 'timeline_clap_marker': 'timeline_clap_marker',
 'timeline_cursor': 'timeline_cursor',
 'timeline_take_marker': 'timeline_take_marker',
 'layout_panel_status': 'layout_panel_status',
 'layout_selected_cell': 'layout_selected_cell',
 'layout_zone_label': 'layout_zone_label',
 'khr_input_marker': 'khr_input_marker',
 'khr_output_marker': 'khr_output_marker',
 'khr_status': 'khr_status',
 'nextion_level_xyz_va0_val': 'nextion_level_xyz_va0_val',
 'nextion_level_xyz_va1_val': 'nextion_level_xyz_va1_val',
 'nextion_level_xyz_va2_val': 'nextion_level_xyz_va2_val',
 'sensor_temp_c': 'sensor_temp_c',
 'temperature_c': 'sensor_temp_c',
 'sensor_light_lux': 'sensor_light_lux',
 'light_lux': 'sensor_light_lux',
 'sensor_xyz': 'sensor_xyz',
 'sensor_level_z': 'level_z',
 'step_dir_stream': 'step_dir_stream',
 'protocol_tick': 'step_dir_stream',
 'ehr_axis_curve': 'ehr_axis_0_curve',
 'ehr_step_preview': 'ehr_axis_0_step_preview',
 'ehr_axis_metrics': 'ehr_axis_0_metrics',
 'axis_0_step': 'step_dir_stream',
 'axis_1_step': 'step_dir_stream',
 'axis_2_step': 'step_dir_stream',
 'axis_3_step': 'step_dir_stream',
 'axis_4_step': 'step_dir_stream',
 'axis_5_step': 'step_dir_stream',
 'axis_0_dir': 'axis_0_dir',
 'axis_1_dir': 'axis_1_dir',
 'axis_2_dir': 'axis_2_dir',
 'axis_3_dir': 'axis_3_dir',
 'axis_4_dir': 'axis_4_dir',
 'axis_5_dir': 'axis_5_dir',
 'axis_0_ctr': 'step_dir_stream',
 'axis_1_ctr': 'step_dir_stream',
 'axis_2_ctr': 'step_dir_stream',
 'axis_3_ctr': 'step_dir_stream',
 'axis_4_ctr': 'step_dir_stream',
 'axis_5_ctr': 'step_dir_stream',
 'take_time_ms': 'take_time_ms',
 'take_number': 'take_number',
 'take_status': 'take_status',
 'par_log': 'par_log',
 'log_event': 'par_log',
 'system_status': 'system_status',
 'par_error': 'par_error',
 'tfd_tc': 'take_timecode',
 'par_mode': 'par_mode',
 'sensor_limits_status': 'sensor_limits_status',
 'sensor_shock_state': 'sensor_shock_state',
 'sensor_laser_set': 'sensor_laser_set',
 'axis_cam_h_pulses': 'axis_0_value',
 'axis_cam_v_pulses': 'axis_1_value',
 'axis_cam_t_pulses': 'axis_2_value',
 'axis_cam_f_pulses': 'axis_3_value',
 'axis_arm_h_pulses': 'axis_4_value',
 'axis_arm_v_pulses': 'axis_5_value',
 'level_x': 'level_x',
 'level_y': 'level_y',
 'live_test_mode': 'par_mode',
 'tfd_title': 'tfd_title',
 'take_title': 'tfd_title',
 'movie_title': 'tfd_title',
 'title': 'tfd_title',
 'tfd_director': 'tfd_director',
 'take_director': 'tfd_director',
 'movie_director': 'tfd_director',
 'director': 'tfd_director',
 'take_tc': 'take_timecode',
 'tc': 'take_timecode',
 'timecode': 'take_timecode',
 'TAKE_TIME_MS': 'take_time_ms',
 'TAKE_TC': 'take_timecode',
 'take_version': 'take_number',
 'take_file': 'take_number',
 'take_path': 'take_number',
 'active_take_path': 'take_number',
 'level_z': 'level_z',
 'shock_state': 'sensor_shock_state',
 'laser_state': 'sensor_laser_set',
 'axis_cam_h_dir': 'axis_0_dir',
 'axis_cam_v_dir': 'axis_1_dir',
 'axis_cam_t_dir': 'axis_2_dir',
 'axis_cam_f_dir': 'axis_3_dir',
 'axis_arm_h_dir': 'axis_4_dir',
 'axis_arm_v_dir': 'axis_5_dir',
 'axis_cam_h_pos': 'axis_0_value',
 'axis_cam_v_pos': 'axis_1_value',
 'axis_cam_t_pos': 'axis_2_value',
 'axis_cam_f_pos': 'axis_3_value',
 'axis_arm_h_pos': 'axis_4_value',
 'axis_arm_v_pos': 'axis_5_value',
 'loaded_take_path': 'take_number',
 'take_label': 'take_number',
 'axis_cam_h_auto_dir': 'axis_0_dir',
 'axis_cam_h_rec_dir': 'axis_0_dir',
 'axis_cam_h_step': 'step_dir_stream',
 'axis_cam_h_auto_step': 'step_dir_stream',
 'axis_cam_h_rec_step': 'step_dir_stream',
 'axis_cam_v_auto_dir': 'axis_1_dir',
 'axis_cam_v_rec_dir': 'axis_1_dir',
 'axis_cam_v_step': 'step_dir_stream',
 'axis_cam_v_auto_step': 'step_dir_stream',
 'axis_cam_v_rec_step': 'step_dir_stream',
 'axis_arm_t_pulses': 'axis_2_value',
 'axis_arm_t_pos': 'axis_2_value',
 'axis_arm_t_dir': 'axis_2_dir',
 'axis_arm_t_auto_dir': 'axis_2_dir',
 'axis_arm_t_rec_dir': 'axis_2_dir',
 'axis_arm_t_step': 'step_dir_stream',
 'axis_arm_t_auto_step': 'step_dir_stream',
 'axis_arm_t_rec_step': 'step_dir_stream',
 'axis_cam_f_auto_dir': 'axis_3_dir',
 'axis_cam_f_rec_dir': 'axis_3_dir',
 'axis_cam_f_step': 'step_dir_stream',
 'axis_cam_f_auto_step': 'step_dir_stream',
 'axis_cam_f_rec_step': 'step_dir_stream',
 'axis_arm_h_auto_dir': 'axis_4_dir',
 'axis_arm_h_rec_dir': 'axis_4_dir',
 'axis_arm_h_step': 'step_dir_stream',
 'axis_arm_h_auto_step': 'step_dir_stream',
 'axis_arm_h_rec_step': 'step_dir_stream',
 'axis_arm_v_auto_dir': 'axis_5_dir',
 'axis_arm_v_rec_dir': 'axis_5_dir',
 'axis_arm_v_step': 'step_dir_stream',
 'axis_arm_v_auto_step': 'step_dir_stream',
 'axis_arm_v_rec_step': 'step_dir_stream',
 'rec_p17_bridge_play_dir_x': 'axis_0_dir',
 'rec_p20_bridge_play_ctr_x': 'step_dir_stream',
 'rec_p18_bridge_play_dir_y': 'axis_1_dir',
 'rec_p21_bridge_play_ctr_y': 'step_dir_stream',
 'tfd_save_status': 'tfd_save_status',
 'tfd_save_status_visible': 'tfd_save_status_visible',
 'tfd_save_sound': 'tfd_save_sound',
 'par_axis_0_val': 'axis_0_value',
 'par_axis_0_dir': 'axis_0_dir',
 'par_axis_1_val': 'axis_1_value',
 'par_axis_1_dir': 'axis_1_dir',
 'par_axis_2_val': 'axis_2_value',
 'par_axis_2_dir': 'axis_2_dir',
 'par_axis_3_val': 'axis_3_value',
 'par_axis_3_dir': 'axis_3_dir',
 'par_axis_4_val': 'axis_4_value',
 'par_axis_4_dir': 'axis_4_dir',
 'par_axis_5_val': 'axis_5_value',
 'par_axis_5_dir': 'axis_5_dir',
 'rrp_p1_value': 'rrp_p1_value',
 'rrp_p1_dir': 'rrp_p1_dir',
 'rrp_p2_value': 'rrp_p2_value',
 'rrp_p2_dir': 'rrp_p2_dir',
 'tfd_title_pco': 'tfd_title_pco',
 'tfd_director_pco': 'tfd_director_pco',
 'take_clap_start': 'take_clap_start',
 'take_clap_stop': 'take_clap_stop',
 'take_tc_running': 'take_tc_running',
 'nextion_audio_event': 'nextion_audio_event',
 'nextion_audio_key': 'nextion_audio_event',
 'nextion_audio_rev': 'nextion_audio_event'}


def resolve_caliber(raw_signal: str) -> str | None:
    """Zwraca logiczną nazwę sygnału Snajpera dla nazwy wejściowej."""
    return DEFAULT_TARZAN_SNAJPER_SIGNAL_MAP.get(raw_signal)
